create table author (
                        author_id int8 generated by default as identity,
                        name varchar(255) not null ,
                        primary key (author_id)
);
create table book (
                         book_id int8 generated by default as identity,
                         title varchar(255) not null ,
                         author_id int8 not null,
                         primary key (book_id)
);

create table author_book(
    author_id int8,
    book_id int8,
    primary key (author_id,book_id)
);

alter table if exists book
    add constraint book_author_id_FK
        foreign key (author_id) references author;